// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8BUI5NYN46EsIbQ6a31jAHLvZu9R6pV4',
    appId: '1:682484606200:web:97577b1d3a4d6df732870d',
    messagingSenderId: '682484606200',
    projectId: 'asn-center-21fa8',
    authDomain: 'asn-center-21fa8.firebaseapp.com',
    storageBucket: 'asn-center-21fa8.appspot.com',
    measurementId: 'G-1Z5ZS6ZK2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUf05Cg-y2PYggQM9yjXSw8I5ffV49TX4',
    appId: '1:682484606200:android:cae98d2a0d294bdd32870d',
    messagingSenderId: '682484606200',
    projectId: 'asn-center-21fa8',
    storageBucket: 'asn-center-21fa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW6X-KaAJ-4QDuwwJiDTj_Ca3NjSyZS6Y',
    appId: '1:682484606200:ios:faea7bd4ccdd15d132870d',
    messagingSenderId: '682484606200',
    projectId: 'asn-center-21fa8',
    storageBucket: 'asn-center-21fa8.appspot.com',
    iosBundleId: 'com.example.asnCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW6X-KaAJ-4QDuwwJiDTj_Ca3NjSyZS6Y',
    appId: '1:682484606200:ios:1140ad33df611a9832870d',
    messagingSenderId: '682484606200',
    projectId: 'asn-center-21fa8',
    storageBucket: 'asn-center-21fa8.appspot.com',
    iosBundleId: 'com.example.asnCenter.RunnerTests',
  );
}
